BJ-988: Schedulator integration
rbkmoney/three-ds-server pull request #24
Opened 2020-09-18 07:59 UTC by rbk-aromanov

https://rbkmoney.atlassian.net/browse/BJ-988

2020-09-18 09:11 UTC, vitaxa reviewed
Не увидел имплементации ScheduledJobExecutorSrv.Iface чтоб обрабатывать callback'и от schedulator'а

2020-09-18 09:11 UTC, vitaxa commented on src/main/java/com/rbkmoney/threeds/server/service/schedule/RBKMoneyPreparationFlowScheduler.java
> +        updatePreparationFlowScheduledJobs();
Если я не ошибаюсь, то тут хорошо бы добавить try catch. Иначе возможна ситуация, когда при ошибке приложение совсем не стартанет

2020-09-18 09:13 UTC, rbk-aromanov commented on src/main/java/com/rbkmoney/threeds/server/service/schedule/RBKMoneyPreparationFlowScheduler.java
> +        updatePreparationFlowScheduledJobs();
Все вызовы шедулатора итак обернуты в try-catch в SchedulatorService. Зачем здесь?

2020-09-18 09:13 UTC, rbk-aromanov commented
> Не увидел имплементации ScheduledJobExecutorSrv.Iface чтоб обрабатывать callback'и от schedulator'а

Будет в другом сервисе – three-ds-server-storage.

2020-09-18 09:15 UTC, vitaxa commented on src/main/java/com/rbkmoney/threeds/server/service/schedule/RBKMoneyPreparationFlowScheduler.java
> +        updatePreparationFlowScheduledJobs();
Ну да, вроде больше нигде exception не должен вылететь, если так, то норм

2020-09-18 09:17 UTC, vitaxa commented
> > Не увидел имплементации ScheduledJobExecutorSrv.Iface чтоб обрабатывать callback'и от schedulator'а
> 
> Будет в другом сервисе – three-ds-server-storage. Этот ответственен только за регистрацию.

Интересно, ну должно быть норм все

2020-09-18 09:21 UTC, vitaxa approved these changes
От меня апрув)

2020-09-19 15:20 UTC, karleowne requested changes

2020-09-19 15:20 UTC, karleowne commented on src/main/java/com/rbkmoney/threeds/server/service/schedule/SchedulatorService.java
> +        String jobId = scheduleProperties.getJobIdPrefix() + dsProviderId;
вопрос.
джоба уникальна в рамках 
String jobId = scheduleProperties.getJobIdPrefix() + dsProviderId;
?
и если другая нода приходит в шедулатор с тем же айдишником, то запрос на джобу будет проигнорирован?

2020-09-19 15:20 UTC, karleowne commented on src/main/resources/application.yml
> -    cron: "-"
у нас 2 источника для запросов в DS по PReq — 
1) при старте сервиса (вижу по шедулатору , что такой запрос произойдет)
2) крон — раз в какой то промежуток времени (допустим, при запуске запрос и потом через каждый час-два повторный запрос в DS для обновления кард ренжей) во время работы сервиса для периодического апдейта согласно спецификации. по коду вижу, что крон удален, но либо не понимаю либо это не вижу, что подобные запросы будут в дальнейшем проходить

2020-09-19 15:26 UTC, vitaxa commented on src/main/java/com/rbkmoney/threeds/server/service/schedule/SchedulatorService.java
> +        String jobId = scheduleProperties.getJobIdPrefix() + dsProviderId;
Если будет второй запрос, то упадет с ScheduleAlreadyExists. И он тут обрабатывается

2020-09-21 07:48 UTC, rbk-aromanov commented on src/main/resources/application.yml
> -    cron: "-"
Шедулатор как раз и занимается отправкой запросов с заданной периодичностью. Расписание надо в доминанте прописать будет.

2020-09-21 08:05 UTC, rbk-aromanov commented on src/main/resources/application.yml
> -    cron: "-"
Кроном, как раз, шедулатор заведует. Нужно будет завести расписание в доминанте.

С вызовом на старте сложнее. Через шедулатор его не сделаешь. Кажется, он не критичен, потому что, по сути, он нужен только один раз в жизни сервиса – при непрогретом сторадже. Если preparation flow хотя бы раз прошло, то в сторадже уже есть какие-то ренджи, с которыми можно работать, а в течение максимум часа пройдет кол от шедулатора и они обновятся. 

Возможно, можно сделать доработку в шедулатор с методом в духе `registerAndCall()`, чтобы при регистрации джобы он ее сразу дергал.

2020-09-21 15:04 UTC, karleowne approved these changes

2020-09-22 07:29 UTC, merged